# Generated by Django 6.0 on 2026-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Documentary', 'Documentary'), ('Animation', 'Animation')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('video_file', models.FileField(upload_to='videos/original/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
